# NixOS Laptop host configuration - placeholder for future setup
{
  self,
  pkgs,
  username,
  inputs,
  ...
}:
{
  imports = [
    ../../modules/nixos
    # ./hardware-configuration.nix  # Generated by nixos-generate-config
  ];

  # Host-specific settings
  networking.hostName = "nixos-laptop";

  # Primary user for this machine
  users.users.${username} = {
    isNormalUser = true;
    description = "Mikael Siidorow";
    extraGroups = [ "networkmanager" "wheel" "docker" ];
    shell = pkgs.zsh;
  };

  # System state version - set this when you first install NixOS
  # and don't change it unless you understand the implications
  system.stateVersion = "24.11";
}
